# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.19.0
      uses: actions/setup-node@v4
      with:
        node-version: 22.19.0
        cache: 'npm'
    - run: npm i
    - name: Build app
      run: npm run build
    - name: Discord success report
      if: ${{ success() }}
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        noprefix: ture
        title: "✅ Build successful"
        username: Github Build
        
    - name: Discord failure report
      if: ${{ failure() }}
      
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        nodetail: true
        title: "Application build was a failure"
        description: "CI testbuild \nfailed"
